--This will combine the 2 table of flights into one table


truncate table TAFLIGHTS;

insert into TAFLIGHTS (LAUNCHTIME,  LANDINGTIME,  PLANEREGISTRATION,  PILOT1INIT,  PILOT2INIT,  LAUNCHAEROTOW,  LAUNCHWINCH,  LAUNCHSELFLAUNCH,  CABLEBREAK
                        , CROSSCOUNTRYKM, CLUB)

  select LAUNCHTIME
      ,  LANDINGTIME
      ,  PLANEREGISTRATION
      ,  PILOT1INIT
      ,  PILOT2INIT
      ,  LAUNCHAEROTOW
      ,  LAUNCHWINCH
      ,  LAUNCHSELFLAUNCH
      ,  CABLEBREAK
      ,  CROSSCOUNTRYKM
      ,  'SG70' as CLUB     
      
  from TAFLIGHTSSG70;
  


  
  
insert into TAFLIGHTS (LAUNCHTIME,  LANDINGTIME,  PLANEREGISTRATION,  PILOT1INIT,  PILOT2INIT,  LAUNCHAEROTOW,  LAUNCHWINCH,  LAUNCHSELFLAUNCH,  CABLEBREAK
                        , CROSSCOUNTRYKM, CLUB)

  select LAUNCHTIME
      ,  LANDINGTIME
      ,  PLANEREGISTRATION
      ,  PILOT1INIT
      ,  PILOT2INIT
      ,  LAUNCHAEROTOW
      ,  LAUNCHWINCH
      ,  LAUNCHSELFLAUNCH
      ,  CABLEBREAK
      ,  CROSSCOUNTRYKM
      ,  'Vejle' as CLUB     
      
  from TAFLIGHTSVEJLE;
    